name: coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  coverage:
    uses: FixPortal/fixportal-workflows/.github/workflows/dotnet-coverage.yml@cf9927d1fdd049dc4a149afbaa18668ace2f9287 # v1.0.0
    with:
      solution: FixPortal.Ci.Backend.slnx
